# Generated by Django 3.1.7 on 2021-04-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_wordcloud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordCloud',
            new_name='HashtagCloud',
        ),
    ]
