# Generated by Django 3.1.7 on 2021-04-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_price'),
        ('articles', '0006_auto_20210422_1555'),
    ]

    operations = [
    ]
