# Generated by Django 3.1.7 on 2021-05-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_merge_20210428_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashtagCloud',
        ),
    ]
