# Generated by Django 3.1.7 on 2021-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_merge_20210428_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashtagCloud',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='article_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
