# Generated by Django 3.1.7 on 2021-04-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210429_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='article_cnt',
        ),
    ]
